global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:3000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
#Queries
# sum(rate(api_request_count[1m])) by (route)   count of requests
# sum(rate(http_request_duration_ms_count{code=~"4..|5.."}[1m])) by (route)  count of errors
# histogram_quantile(0.95, sum(rate(http_request_duration_ms_bucket[5m])) by (le, route)) 95th percentile of response time
