#  kind create cluster --config kind.yml --name local2
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30007
        hostPort: 30007
  - role: worker
    extraPortMappings:
      - containerPort: 30007
        hostPort: 30008
  - role: worker
# ARGOCD
# kubectl port->forward service/argocd-server -n argocd 8080:443
# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
